EXPLICACOES = {
"inicio":("Início do Motor","A página inicial prioriza os três regimes. Cadastros e históricos existem para apoiar o cálculo."),
"simples":("Simples Nacional","Calcula o DAS estimado conforme Anexo, RBT12, faixa, alíquota efetiva e segregações informadas. Confira no PGDAS-D antes de transmitir."),
"rbt12":("RBT12","Receita bruta acumulada usada para localizar a faixa. No início de atividade, o motor aplica a proporcionalização parametrizada e mostra a memória."),
"fs12":("FS12","Folha considerada para o Fator R. É formada a partir dos componentes informados no histórico e deve ser conferida pelo responsável."),
"fator_r":("Fator R","Relação entre FS12 e RBT12 para atividades sujeitas ao Fator R. O motor usa o corte parametrizado de 28% e mostra o Anexo aplicado."),
"anexo":("Anexo do Simples","Define faixas, alíquotas e repartição. A sugestão por CNAE só é automática quando a base tributária estiver validada."),
"segregacao":("Segregação de receitas","Separe receitas por natureza. Monofásico, ICMS-ST, exportação e ISS retido podem retirar parcelas específicas do DAS."),
"monofasico":("Monofásico","Retira PIS/Pasep e Cofins da parcela do DAS marcada, mas a natureza monofásica do item precisa ser validada externamente."),
"icms_st":("ICMS-ST","Retira ICMS da composição da receita marcada quando o usuário confirma o tratamento. O sistema não classifica a mercadoria sozinho."),
"iss_retido":("ISS retido","Pode retirar ISS da parcela correspondente quando corretamente caracterizado. Confirme retenção, município e regra aplicável."),
"exportacao":("Exportação","Aplica exclusões parametrizadas conforme o Anexo e mostra o efeito por tributo para conferência."),
"sublimite":("Sublimite ICMS/ISS","A V5 alerta quando o RBT12 supera o sublimite parametrizado, mas só retira ICMS/ISS do DAS após confirmação explícita."),
"presumido":("Lucro Presumido","Apura cenário trimestral de IRPJ/CSLL por presunção, PIS/Cofins cumulativos e parâmetros de ISS, ICMS e CPP."),
"presuncao_mista":("Atividades mistas","Cada atividade recebe seu percentual de presunção. O limite de 2026 é distribuído proporcionalmente entre as receitas operacionais."),
"receitas_financeiras":("Receitas financeiras","Entram separadamente e integralmente nas bases gerenciais de IRPJ/CSLL do cenário. Não recebem presunção operacional."),
"ganho_capital":("Ganho de capital","É informado separadamente e agregado integralmente às bases gerenciais. O valor deve vir de apuração fiscal adequada."),
"pis_cofins_presumido":("PIS/Cofins no Presumido","Usa regime cumulativo padrão sobre receitas operacionais do cenário. Tratamentos específicos devem ser validados à parte."),
"real":("Lucro Real — Beta","Parte do lucro contábil e aplica ajustes e compensações informados. Não decide sozinho dedutibilidade, tributabilidade ou elegibilidade de créditos."),
"lucro_contabil":("Lucro contábil","É o ponto de partida do Lucro Real informado pelo profissional, e não uma simples receita menos despesa calculada pela tela."),
"adicoes":("Adições e exclusões","Podem ser informadas por total e detalhadas por lançamento, com descrição e fundamento para memória de cálculo."),
"prejuizo":("Prejuízo fiscal / base negativa","No cenário geral a V5 aplica a trava parametrizada de 30% do lucro ajustado positivo. Exceções exigem análise profissional."),
"csll":("CSLL parametrizável","O padrão geral fica parametrizado, mas a tela permite informar alíquota diferente quando o profissional souber que há regra específica."),
"pis_cofins_real":("PIS/Cofins não cumulativos","Calcula débitos e desconta créditos informados. A V5 não valida juridicamente cada crédito."),
"comparador":("Comparador tributário","Compara cenários disponíveis com os dados informados e usa a expressão 'cenário estimado mais econômico', nunca uma ordem de enquadramento."),
"qualidade_comparacao":("Qualidade da comparação","Alta quando os três cenários possuem dados suficientes; média/baixa quando algum regime não pode ser calculado com qualidade equivalente."),
"empresa":("Empresa / cálculo avulso","Vincular empresa permite usar histórico e salvar resultados. Os motores também aceitam cálculo avulso."),
"cnpj":("CNPJ","Cadastro manual valida os dígitos verificadores antes de gravar."),
"consulta_cnpj":("Consulta externa de CNPJ","Busca dados de conveniência em serviço externo. Sempre confira no comprovante oficial da Receita Federal."),
"pdf_cnpj":("PDF de CNPJ","Valida assinatura básica, limita tamanho, extrai dados e remove o arquivo temporário após processar."),
"xml":("XML NF-e","Parser seguro extrai totais e sinaliza indícios de ST/monofásico. Indício não significa confirmação do tratamento fiscal."),
"historico":("Histórico","Guarda resultados salvos, memória e versão da regra. Pode ser exportado em CSV."),
"fechamento":("Fechamento de competência","Bloqueia alterações de faturamento, folha e apuração. Somente administrador pode reabrir competência fechada."),
"versao_regra":("Versão da regra","Cada cálculo registra a versão parametrizada utilizada para preservar rastreabilidade histórica."),
"pdf_relatorio":("Relatório PDF","Exporta resumo, composição, alertas e memória. É apoio interno e não substitui obrigação oficial."),
"csv":("Exportação CSV","Gera histórico tabular para conferência em planilha."),
"usuarios":("Usuários e papéis","Administrador cria usuários. Operadores usam motores; ações administrativas sensíveis ficam restritas."),
"seguranca":("Segurança","Em produção exige SECRET_KEY e DATABASE_URL, usa CSRF, hash de senha, rate limit, cookies seguros e sessão expirada."),
"memoria":("Memória de cálculo","Mostra fórmulas, bases, parâmetros e versões usadas para que o resultado possa ser conferido."),
"auditoria":("Auditoria","Registra usuário, empresa, ação, registro, IP e horário nas principais operações."),
"competencia":("Competência","Período de referência. A V5 consolida faturamento, folha, RBT12/FS12 e status em uma camada de competência sem apagar o histórico anterior."),
"iss_icms":("ISS / ICMS estimados","Parâmetros gerenciais informados; não substituem apuração municipal/estadual."),
"cpp":("CPP","Valor informado para compor o cenário quando aplicável; confirme a forma de recolhimento do regime/atividade."),
"regra_2026":("Regra 2026","Os parâmetros de 2026 ficam em arquivos versionados, com metadados/checksum registrados no banco."),
"salvar":("Salvar cálculo","Quando marcado e há empresa vinculada, o resultado entra no histórico e na trilha de auditoria."),
}
